# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule: 
    - cron: '0 17 * * 1-5'
    - cron: '0 15 * * 6,0'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set argument
        id: set-argument
        run: |
          DAY_OF_WEEK=$(date +%u)
          case "$DAY_OF_WEEK" in
            6|0)
                echo "ARG='17:40'" >> $GITHUB_ENV
                ;;
            1|2|3|4|5)
                echo "ARG='20:40'" >> $GITHUB_ENV
                ;;
            *) 
                echo "Not expected value"
                exit 0
          esac


      - name: Run script
        env:
          KAMAR_BOT_TOKEN: ${{ secrets.KAMAR_BOT_TOKEN }}  # Use the secret here
        run: |
          python bot.py $ARG
